backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "markdown"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Cover Image", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "md-upload"
    label: "Upload Markdown file"
    files:
      - label: "Upload markdown as file"
        name: "upload_md"
        file: "content/posts/{{slug}}.md"
        fields:
          - {label: "Slug (filename)", name: "slug", widget: "string"}
          - {label: "Body (raw markdown)", name: "body", widget: "markdown"}
